### ISSUE TITLE
Stable release v1.0.0

### ISSUE THREAD

**Issue by yudai-nkt** [yudai-nkt/language-tex#10]
With the release of [v0.3.0](https://github.com/yudai-nkt/language-tex/releases/tag/v0.3.0), I almost finished what I've initially wanted to implement. I am planning to do refactoring and something to release v1.0.0, which will be developed in [version1](https://github.com/yudai-nkt/language-tex/tree/version1) branch (of course, bug fixes and minor updates will be made alongside).

Here is a list of tweaks I want to do before the major release. Some points perhaps skip my mind at the moment and they will be added once I remember again.
### Unification of backslash and letters in pattern matching

In the original package converted from TextMate bundle, the backslashes of many control sequences are set to `punctuation.definition` attribute like the snippet below:

``` cson
'captures':
  '1':
    'name': 'punctuation.definition.keyword.tex'
```

This causes bad highlighting with some syntax themes. For example, code from `latex.cson`

``` cson
# this is converted from TextMate
1736 'captures':
1737   '0':
1738     'name': 'keyword.other.item.latex'
1739   '1':
1740     'name': 'punctuation.definition.keyword.latex'
1741 'match': '(\\\\)item\\b'
1742 'name': 'meta.scope.item.latex'
# this is added by me
1774 'begin': '(\\\\bibitem)(\\{)'
1775 'beginCaptures':
1776   '1':
1777     'name': 'keyword.control.bibitem.latex'
1778   '2':
1779     'name': 'punctuation.definition.arguments.begin.latex'
```

results in the following appearance with [Seti Syntax](https://atom.io/themes/seti-syntax) (line numbers and comments are added by me and line numbers are as of 7d5bb5c05057dc9b828e6ee3870ae5e448e4dd04). You will notice that it's hard to find the leading backslash of `\item` compared to that of `\bibitem`.

![2016-08-29 3 35 19](https://cloud.githubusercontent.com/assets/13291527/18035886/acc191d4-6d99-11e6-9bbc-f6de0ad61d33.png)

TeXnically speaking, a control sequence, say `\foo`, is composed of two parts; an escaped character `\` and a sequence of available letters `foo` assuming default category codes. That being said, control sequence is a _single_ token and I believe it should be highlighted in a consistent manner.
### Overuse of `begin`/`end` keys

There are many unnecessary use of keys that enable pattern-matching over multiple lines. For example, inline math `$...$` is [breakable](https://github.com/yudai-nkt/language-tex/blob/31c246c5d3355c62770467162c3201769322a0a8/grammars/tex.cson#L71-L89) and this causes terrible highlight in package files that have unbalanced dollar sign in the definition of its macros (e.g., try `atom $(kpsewhich mathtools.sty)` and check line 1517 or later in v1.18).
### Sorting order

In the current product, different grammars entry have different order of keys and this is not a good practice from the viewpoint of consistency of codes. Order of each grammar entry is not decided neither. How to arrange the orders of them must be decided.
### Module

`latex.cson` now has 2000+ lines and if it keeps getting bigger, it will be hard to maintain. Modularization by utilizing `repository` feature per packages or something might help. This is relevant to the issue above.
### Effective use of scope

In v0.2.0, math snippets are allowed to be expanded only in math mode. Such kind of scope use will enhance our experience of writing LaTeX code e.g.,
- snippet for `\usepackage` is only allowed in preamble
- `\bibitem{foo}` should be highlighted only in `thebibliography` environment
- etc.
### Removal of ugly comments

I suppose that [this](https://github.com/yudai-nkt/language-tex/blob/7d5bb5c05057dc9b828e6ee3870ae5e448e4dd04/grammars/latex.cson#L61) kind of comments can safely be deleted (actually I do not understand why these `\t`s etc. do not affect the grammar).
### Naming scheme

We have [TextMate manual](http://manual.macromates.com/en/language_grammars.html#naming_conventions) regarding how to `name` each attribute. (La)TeX is somewhat different from many other _usual_ programming language, however, so naming scheme should be well considered again.
### Preparation of contribution guide

Last but most importantly, adopted decisions have to be explicitly documented. This serves as a reminder for me as well as a guideline for future contributors.

---

I opened this issue just to use as a record of my thoughts and a ToDo list, but any kinds of opinion, be it in favor of or against, of those who find this issue are greatly appreciated. I do not only appreciate but **NEED** also. Some of the changes I want to make might be a bit subjective, so they are worth discussion.

**Comment by yudai-nkt** [comment]
Closing this because I'm now a collaborator of [`language-latex`](https://github.com/area/language-latex/) package.

**Comment by Aerijo** [comment]
For what it's worth, the broken syntax on the mathtools.sty file is because it uses latex3 syntax, which isn't supported at all (yet). 

I happen to like multiline pattern matching, as it allows the author to write in their own way. For example, the usepackage regex will only work if everything (including optional arguments) is on one line. I did not like this at all. In fact, it was the reason I made my own package in the first place (that, and it was a fun learning exercise :)

**Comment by yudai-nkt** [comment]
Expl3 syntax is supported with [this part](https://github.com/yudai-nkt/language-tex/blob/master/grammars/latex.cson#L88-L116) and the reason for the broken highlight is an unbalanced dollar sign (`mathtools.sty` is just an example).

> the usepackage regex will only work if everything (including optional arguments) is on one line. I did not like this at all

I agree with you in this point and I'd like to make it possible to split `\usepackage` syntax in the package option (this is one of the future improvements).

**Comment by Aerijo** [comment]
That part does support it, but the mathtools package fails near the start because it uses `\MHInternalSyntaxOn` to begin, and that part only looks for `\ExplSyntaxOn`. I don't think there's much that can be done here though, aside from listing every known way of starting l3 syntax.

You can draw inspiration from [here](https://github.com/Aerijo/language-latex2e/blob/7988e0bf4a19fbe1eeda14b9751125c55f12d012/grammars/latex.cson#L271) if you like. It looks weird, but it works for me. It even does some linting, as it will mark characters between `\usepackage` and `{}` as errors. I think it does some other stuff too, but I forget.
