### ISSUE TITLE
Issue with Highlighting when Braces are Nested

### ISSUE THREAD

**Issue by jdw1996** [yudai-nkt/language-tex#11]
In some constructs, all of the text between a pair of curly braces should be highlighted, but I am having an issue where this text is not always highlighted. I've attached an image to show what I mean (see the arguments to `section` and `emph`). It seems that the problem is caused by nested curly braces, as used when adding accents to a character. I don't have this issue when I use `language-latex` instead.

I'm using Atom 1.10.2 on Ubuntu 16.04.

Unfortunately I don't have any experience with CoffeeScript, but let me know if there's anything I can do to help resolve this issue.

![passe_compose](https://cloud.githubusercontent.com/assets/17225098/18486700/28e8c250-79c0-11e6-819c-cd8116c69195.png)

**Comment by yudai-nkt** [comment]
I could confirm your issue. This bug exactly resulted from the nested curly braces and appeared in a4f3f85ced8798e0166ea55594b419c00386b15a, so I reverted the commit. Feel free to reopen the issue if you still see this problem after trying the new version v0.3.1.

**Comment by jdw1996** [comment]
I just updated and it's working perfectly now. Thanks for taking care of it so quickly!
