### ISSUE TITLE
Support highlighting in markdown file and its preview?

### ISSUE THREAD

**Issue by Edenharder** [yudai-nkt/language-tex#13]
What I want to do is: the latex code will be highlighted when I insert it in the markdown file. 

For example, if the language python is enabled, then python code will be highlighted as following.
![image](https://cloud.githubusercontent.com/assets/6672134/19759048/60b96d8c-9c2b-11e6-8d44-c2220b2104bb.png)

The left one is in the markdown file while the right one is in the preview.

**Comment by yudai-nkt** [comment]
I now work on `language-latex` package (and you seem to report the same issue at area/language-latex#98), so will close this one.
