### ISSUE TITLE
Minted embeds - problem with characters prepending `\begin{minted}` command

### ISSUE THREAD

**Issue by pathes** [yudai-nkt/language-tex#8]
If there are any characters (even whitespace) prepending the `\begin{minted}` command,
the following lines won't be recognised as an embedded source fragment.
![screenshot from 2016-08-04 23-32-07](https://cloud.githubusercontent.com/assets/2782408/17419017/c1ecfc9e-5a9b-11e6-911c-eed28fb2575a.png)

**Comment by yudai-nkt** [comment]
Hi, thanks for the report.

I could reproduce your problem and it should be resolved in 825676a384e54704021a009766f0bd5c4a91c78e. I will release v0.2.1 later, and feel free to reopen the issue if the problem still remains with the upcoming version.

``` latex
\begin{listing}
    \begin{minted}{python}
        foo = "bar"
    \end{minted}
\end{listing}
\begin{listing}
\begin{minted}{python}
    foo = "bar"
\end{minted}
\end{listing}
```

![2016-08-05 12 03 03](https://cloud.githubusercontent.com/assets/13291527/17425095/a55e4bc8-5b04-11e6-8d22-26eea7f0412e.png)
